//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryEDMConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarID { get; set; }
        public string Make { get; set; }
        public string Color { get; set; }
        public string CarNickname { get; set; }

        public override string ToString()
        {
            // Since the PetName column colud be empty, supply the default name of **No Name**
            return string.Format("{0} is a {1} {2} with ID {3}.",
                this.CarNickname ?? "**No Name**",
                this.Color, this.Make, this.CarID);
        }
        //partial void OnCarNicknameChanging(global::System.String value)
        //{
        //    Console.WriteLine("\t-> Changing name to: {0}", value);
        //}
        //partial void OnCarNicknameChanged()
        //{
        //    Console.WriteLine("\t-> Name of car has been changed!");
        //}
    }
}
